name: commitlint
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node (for commitlint)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install commitlint
        run: |
          npm install --no-save @commitlint/{config-conventional,cli}
      - name: Lint commits
        run: |
          npx commitlint --from=${{ github.event.pull_request.base.sha }} --to=${{ github.event.pull_request.head.sha }}
