name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build ./...

    - name: Run go fmt
      run: go fmt ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.56.2
    - name: Run golangci-lint
      run: golangci-lint run ./...


    - name: Run tests with coverage
      run: go test -coverprofile=coverage.out -covermode=atomic ./...
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.out


    - name: Build Docker image
      run: docker build -t pool-maintenance-api .

    - name: Install Trivy
      run: |
        sudo apt-get update && sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.51.1_Linux-64bit.deb
        sudo dpkg -i trivy_0.51.1_Linux-64bit.deb
    - name: Scan Go dependencies for vulnerabilities
      run: trivy fs --scanners vuln --exit-code 1 --severity HIGH,CRITICAL .
    - name: Scan Docker image for vulnerabilities
      run: trivy image --exit-code 1 --severity HIGH,CRITICAL pool-maintenance-api

    - name: Run Docker container (background)
      run: |
        docker run -d -p 8080:8080 --name pool-maintenance-api-test pool-maintenance-api

    - name: Health check endpoint smoke test
      run: |
        sleep 3
        curl --fail http://localhost:8080/health | grep '"status":"ok"'

    - name: Cleanup Docker container
      if: always()
      run: |
        docker rm -f pool-maintenance-api-test || true
