name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build ./...

    - name: Run go fmt
      run: go fmt ./...

    - name: Run go vet
      run: go vet ./...

    - name: Run tests
      run: go test -v ./...

    - name: Build Docker image
      run: docker build -t pool-maintenance-api .

    - name: Run Docker container (background)
      run: |
        docker run -d -p 8080:8080 --name pool-maintenance-api-test pool-maintenance-api

    - name: Health check endpoint smoke test
      run: |
        sleep 3
        curl --fail http://localhost:8080/health | grep '"status":"ok"'

    - name: Cleanup Docker container
      if: always()
      run: |
        docker rm -f pool-maintenance-api-test || true
